In [1]:
print("Numpy")

Numpy


In [4]:
# Importing The Numpy Library.
import numpy as np

if(np):
    print("Numpy is Loaded")
else:
    print("Numpy is not available!")

Numpy is Loaded


In [6]:
# Creating a Numpy Array!

array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Creating 2_D Array
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Creating an Array from Tuple.
array_3 = np.array((1,2,3,4,5))
print(array_3)
print(type(array_3))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Indexing fom Numpy Array

array_4 = np.array([100,200,300,400,500,600,700,800,900,1000])
print(array_4[:])
print(array_4[0:5])
print(array_4[5:7])
print(array_4[0:])
print(array_4[:7])

# Negative Indexing

print(array_4[-6:-4])
print(array_4[:-1])
print(array_4[-4:-2])

[ 100  200  300  400  500  600  700  800  900 1000]
[100 200 300 400 500]
[600 700]
[ 100  200  300  400  500  600  700  800  900 1000]
[100 200 300 400 500 600 700]
[500 600]
[100 200 300 400 500 600 700 800 900]
[700 800]


In [35]:
# Basic Array Operations

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[2,3],[4,5]])

print("Adding 10 to Each Element : " , (a1+10))
print("Adding 10 to Each Element : " , (a2+20))

print("Subtracting 10 to Each Element : " , (a2-10))

# Getting Sum of Whole Array!

print("Addition of Array 1 : " , a1.sum())

print("Addition of Array 2 : " , a2.sum())

# Performing Binary Array Operations.

print("Addition : ",a1+a2)
print("Subtraction : ",a1-a2)
print("Multiplication : ",a1*a2)
print("Division : ",a1/a2)

Adding 10 to Each Element :  [[11 12]
 [13 14]]
Adding 10 to Each Element :  [[22 23]
 [24 25]]
Subtracting 10 to Each Element :  [[-8 -7]
 [-6 -5]]
Addition of Array 1 :  10
Addition of Array 2 :  14
Addition :  [[3 5]
 [7 9]]
Subtraction :  [[-1 -1]
 [-1 -1]]
Multiplication :  [[ 2  6]
 [12 20]]
Division :  [[0.5        0.66666667]
 [0.75       0.8       ]]


In [36]:
# Numpy Functions!

# .zeros((row,col)) - create pure zero array for specific Row and Column
Array_of_Zeros = np.zeros((3,3))
print(Array_of_Zeros)
print(type(Array_of_Zeros))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [37]:
# .ones((row,col)) - Create Pure Array with 1 Value for Specific Row and Column
Array_of_ones = np.ones((5,5))
print(Array_of_ones)
print(type(Array_of_ones))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [39]:
# .range(starting number, ending number, skipping Value)

Arrays_of_Ranges = np.arange(0,10,2)
print(Arrays_of_Ranges)
print(type(Arrays_of_Ranges))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [ ]:
# Getting Exponential of an Array
print(np.exp(Arrays_of_Ranges)) 

# Getting Square Root of Array Elements
print(np.exp(array_4))

[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03]
[2.68811714e+043 7.22597377e+086 1.94242640e+130 5.22146969e+173
 1.40359222e+217 3.77302030e+260 1.01423205e+304             inf
             inf             inf]


C:\Users\Vraj Suratwala\AppData\Local\Temp\ipykernel_85604\887214704.py:5: RuntimeWarning: overflow encountered in exp
  print(np.exp(array_4))


In [49]:
# Numpy Sorting Arrays

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",np.sort(arr, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [52]:
# Constructing Data Type

# Integer datatype
x = np.array([1, 2])  
print(x.dtype)  
print(x)       
 
# Float datatype
x = np.array([1.0, 2.0]) 
print(x.dtype) 
print(x) 
 
# Forced Datatype
x = np.array([1.0, 2.0], dtype = np.int64)   
print(x.dtype)
print(x)


int32
[1 2]
float64
[1. 2.]
int64
[1 2]


In [56]:
# Transposing an Array

T_Array = np.array([[1,2,3,4,5,6,7,8,9,10],[10,20,30,40,50,60,70,80,90,100]])
T_Array = T_Array.T
print(T_Array)

[[  1  10]
 [  2  20]
 [  3  30]
 [  4  40]
 [  5  50]
 [  6  60]
 [  7  70]
 [  8  80]
 [  9  90]
 [ 10 100]]


In [60]:
# Creating full array with specific elements.

array_full = np.full((3,3),7)
print(array_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [63]:
# Creating an Array using Reshape and arange Method!

array_reshape_range = np.arange(11,20).reshape(3,3)
print(array_reshape_range)
print(type(array_reshape_range))

[[11 12 13]
 [14 15 16]
 [17 18 19]]
<class 'numpy.ndarray'>


In [65]:
# Creating an Array using using random.randint().reshape

array_random_reshape = np.random.randint(100,1000,9).reshape(3,3)
print(array_random_reshape)

[[852 857 430]
 [696 406 803]
 [462 423 965]]


In [67]:
# Getting The Dimension For any Numpy Array

print("Dimension : " , array_random_reshape.ndim)

# Getting size of an Array

print("Size of Array : " , array_random_reshape.size)

# Getting Shape of an Array

print("Shape : " , array_random_reshape.shape)

Dimension :  2
Size of Array :  9
Shape :  (3, 3)


In [71]:
# Getting sum,min and max

print(sum(array_random_reshape))
print(array_random_reshape.min())
print(array_random_reshape.max())

[2010 1686 2198]
406
965


In [72]:
array_5=np.linspace(11,20,4)
array_5.shape=(2,2)
print(array_5)

[[11. 14.]
 [17. 20.]]


In [75]:
# Stat Operations.

print(np.mean(array_5))
print(np.median(array_5))
print(np.std(array_5))


15.5
15.5
3.3541019662496847


In [76]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,30,40,50])

print(np.equal(a,b))
print(np.array_equal(a,b))


[False False  True  True  True]
False


In [77]:
np.vstack((a,b))

array([[10, 20, 30, 40, 50],
       [ 1,  2, 30, 40, 50]])

In [78]:
np.hstack((a,b))

array([10, 20, 30, 40, 50,  1,  2, 30, 40, 50])

In [79]:
np.concatenate((a,b))

array([10, 20, 30, 40, 50,  1,  2, 30, 40, 50])

In [80]:
np.intersect1d(a,b)

array([30, 40, 50])

In [81]:
np.setdiff1d(a,b)

array([10, 20])

In [83]:
np.setdiff1d(b,a)

array([1, 2])

In [84]:
# How to Save The Array?
np.save("Saved_Array",array_5)

In [88]:
# Loading The Array Which we saved!

array_which_was_saved = np.load('Saved_Array.npy')
print(array_which_was_saved)

[[11. 14.]
 [17. 20.]]
